/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "arm_math.h"
#include "clock.h"
#include "adc.h"
#include "signals.h"
#include "fir_filter.h"


#define GPIODEN        (1U << 3)
#define PIN12          (1U << 12)
#define Green_LED_PIN  PIN12

static void pseudo_dly(int dly);

extern float LP_1HZ_2HZ8IMPULSE_RESPONSE[IMP_RESP_LENGTH] ;
extern float LP_1HZ_3HZ_IMPULSE_RESPONSE[IMP_RESP2_LENGTH];

/*Global Variables*/
uint32_t g_sensor_read ;

fir_filter_t lpf_fir;

float32_t fltr_sensor_value;


int main(void)
{
	/*Enable FPU : Enable CP10 and CP11 full access*/
	SCB->CPACR |= ((3UL << 10*2)) | ((3UL << 10*2));

	/*Configure clock tree*/
	clock_100Mhz_config();

	/*Initialize ADC*/
	pa1_adc_init();
	/*start conversion*/
	start_conversion();

	/*Initialize fir filter*/
	fir_fiter_init(&lpf_fir ,LP_1HZ_3HZ_IMPULSE_RESPONSE, IMP_RESP2_LENGTH);


	while(1)
	{
		g_sensor_read = adc_read();

		fltr_sensor_value = fir_filter_update(&lpf_fir, g_sensor_read);

		pseudo_dly(10000);

	}
}

static void pseudo_dly(int dly)
{
	for(int i =0;i < dly;i++){}

}



